version: '3.5'
services:

    rabbitmq:
      image: rabbitmq:management
      environment:
        RABBITMQ_DEFAULT_USER: admin
        RABBITMQ_DEFAULT_PASS: admin
        # RABBITMQ_DEFAULT_VHOST: my_vhost
      ports:
        - "5672:5672"
        - "15672:15672"
